### ISSUE TITLE
HHow to connect Arduino Micro Pro to OLED?

### ISSUE THREAD

**Issue by Saddamko** [awall9999/Arduino-Glass#1]
For Hardware SPI we need 11,12,13 pin. But Micro Pro do not has it.

**Comment by awall9999** [comment]
Hi, the SPI Bus on the pro Picro is on Pin 15(SCLK) and 16(Mosi)
Connect RST to pin 9 (req. for SPI and I2C)
Connect DC to pin 8 (required for SPI)
Connect CS to pin 10 (required for SPI)

**Comment by Saddamko** [comment]
Hi, thanks for help!
For my shame, I don't read documentation on Micro Pro before as placed my question... (

**Comment by awall9999** [comment]
No problem ;)
  
 Cheers
 Alain
  
  
  

----------------------------------------
 Von: "Saddamko" <notifications@github.com>
Gesendet: Donnerstag, 9. März 2017 06:41
An: "awall9999/Arduino-Glass" <Arduino-Glass@noreply.github.com>
CC: "Alain Mauer" <alain.mauer@vo.lu>, "Comment" <comment@noreply.github.com>
Betreff: Re: [awall9999/Arduino-Glass] HHow to connect Arduino Micro Pro to OLED? (#1)   

Hi, thanks for help!
For my shame, I don't read documentation on Micro Pro before as placed my question... (  

-
